#ifndef LOR_UNIQUE_COMPILER_STRING_H
#define LOR_UNIQUE_COMPILER_STRING_H

#ifdef LOR_UNIQUE_COMPILER_STRING
#else
  #ifdef __GNUC__
    #define LOR_UNIQUE_COMPILER_STRING_TO_STRING_HELPER(x)  #x
    #define LOR_UNIQUE_COMPILER_STRING_TO_STRING(x)         LOR_UNIQUE_COMPILER_STRING_TO_STRING_HELPER(x)
    #define LOR_UNIQUE_COMPILER_STRING                      LOR_UNIQUE_COMPILER_STRING_TO_STRING(__COUNTER__)
  #endif
#endif

#endif
